version: '2'

networks:
  ros:
    driver: bridge

services:
  main:
    build:
      context: .
    user: user
    image: nvidia_ros_image
    volumes: 
      - ".:/home/user"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    command: >
      /bin/bash -c "/opt/ros/melodic/env.sh roscore & /opt/ros/melodic/env.sh rosrun rviz rviz"
    networks:
      - ros

  camera:
    build:
      context: .
    user: user
    image: nvidia_ros_image
    volumes: 
      - "./camera_ws:/home/user/camera_ws"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    depends_on:
      - main
    environment:
      - ROS_MASTER_URI=http://main:11311
      - ROS_HOSTNAME=camera"
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    networks:
      - ros
    devices:
      - "/dev/video0:/dev/video0"
    command: >
      /bin/bash -c "source /opt/ros/melodic/setup.bash &&
          cd /home/user/camera_ws &&
          ./build/leopard_cam"

  lidar:
    build:
      context: .
    image: nvidia_ros_image
    user: user
    volumes: 
      - "./lidar_ws:/home/user/lidar_ws"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    depends_on:
      - main
    environment:
      - ROS_MASTER_URI=http://main:11311
      - ROS_HOSTNAME=lidar
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_LOG_DIR=/home/user/lidar_ws/logs
    networks:
      - ros
    command: >
      /bin/bash -c "source /opt/ros/melodic/setup.bash &&
          cd /home/user/lidar_ws &&
          source ./devel/setup.sh &&
          roslaunch livox_ros_driver livox_lidar_rviz.launch --wait"